#!/bin/bash
# ==============================================================================
# File: scripts/configure_gnss.sh
# Description: Auto-detects GNSS hardware (USB vs UART) and configures GPSD.
# ==============================================================================

set -e

echo "[OPS] Detecting GNSS Hardware..."

# 1. Check for SiRF Star IV (Prolific USB) - Used by East/West
if lsusb | grep -qi "Prolific"; then
    GNSS_TYPE="SIRF_USB"
    DEVICE_PATH="/dev/ttyUSB0"
    GPSD_FLAGS="-n" 
    echo " -> Detected: SiRF Star IV (via Prolific USB)"

# 2. Check for u-blox (Native USB) - Used by North
elif lsusb | grep -qi "u-blox"; then
    GNSS_TYPE="UBLOX_USB"
    DEVICE_PATH="/dev/ttyACM0"
    # -b = Binary mode (Essential for u-blox timing)
    # -n = Don't wait for client
    GPSD_FLAGS="-n -b"
    echo " -> Detected: u-blox GNSS (Native USB)"

else
    echo "[!] CRITICAL: No known GNSS hardware found."
    exit 1
fi

# 3. Apply Configuration
CONFIG_FILE="/etc/default/gpsd"
echo "[OPS] applying settings for $GNSS_TYPE..."

cat <<EOF > $CONFIG_FILE
# /etc/default/gpsd
# Auto-generated by configure_gnss.sh
START_DAEMON="true"
DEVICES="$DEVICE_PATH"
GPSD_OPTIONS="$GPSD_FLAGS"
USBAUTO="true"
EOF

# 4. Restart Service
echo "[OPS] Restarting gpsd..."
systemctl restart gpsd
sleep 2

# 5. Validate
if systemctl is-active --quiet gpsd; then
    echo "[SUCCESS] gpsd is active on $DEVICE_PATH"
else
    echo "[FAIL] gpsd failed to start."
    exit 1
fi
